apiVersion: v1
kind: Service
metadata:
  name: orion
  namespace: fiware-test
spec:
  selector:
    app: orion
  type: NodePort
  ports:
  - protocol: TCP
    port: 1026
    targetPort: 1026
    nodePort: 30000